### ISSUE TITLE
[FE] 이슈 목록 기능 정의 및 설계

### ISSUE THREAD

**Issue by 77unny** [codesquad-member-2020/issue-tracker-03#11]
### 이슈 목록 기능 정의 및 설계

- 이슈 리스트 컴포넌트 (이슈 아이템이 모인 리스트, 목록 화면)
- 이슈 아이템 컴포넌트 

각 컴포넌트 구성과 어떤 상태를 가지고 있어야 하는가?

**Comment by 77unny** [comment]
이슈 리스트 및 이슈 아이템의 JSON 형태 (가안)

````json
[
  {
    "issueId": 1, 
    "isOpen" : true, 
    "title" : "이슈 목록 기능 정의",
    "labels" : [
      {
        "name": "FE",
        "color": "#ffffff",
        "bgColor": "#f2b5f1",
      },
    ],
    "writer" : "baekCo",
    "creationTime" : "시간 형태로 출력",
    "milestone" : "1주차"
  },
  {
    "issueId": 2, 
    "isOpen" : true, 
    "title" : "레이블과 마일스톤이 없을 경우",
    "labels" : [],
    "writer" : "baekCo",
    "creationTime" : "시간 형태로 출력",
    "milestone" : null
  }
]
````

**Comment by 77unny** [comment]
이슈 목록 상단 영역 구성 : [ 검색 + 버튼 영역]

![#7-이슈트래커  목록 상단 검색 컨테이너](https://user-images.githubusercontent.com/44539224/84230824-cd9e4f80-ab27-11ea-8165-8d13d43b8666.png)

**Comment by 77unny** [comment]
이슈 목록 구성 - TotalCheckBox / Filter / 아이템 / 아이템리스트 

![#7-이슈트래커  이슈 목록 - 이슈리스트 ](https://user-images.githubusercontent.com/44539224/84233153-b9a91c80-ab2c-11ea-8e0f-1b38503d045e.png)

**Comment by 77unny** [comment]
더미 버전의 레이아웃 구조입니다. 
특히 네이밍은 신경쓰지마세요.. ㅎㅎ 임의로 정의한 네이밍!

**Comment by dev-angelo** [comment]
> 더미 버전의 레이아웃 구조입니다.
> 특히 네이밍은 신경쓰지마세요.. ㅎㅎ 임의로 정의한 네이밍!

@baekCode  작업하신 레이아웃 스케치가 굉장히 깔끔합니다!
따로 특별히 사용하신 툴이 있는건가요?

**Comment by 77unny** [comment]
이슈 리스트 페이지 화면 구성
![이슈리스트페이지 화면 구성](https://user-images.githubusercontent.com/44539224/84251028-bf602b80-ab47-11ea-8129-810e2032475f.png)
