### ISSUE TITLE
[FE] 전체 페이지에서 필요한 Header Container 설계 및 기능 정의

### ISSUE THREAD

**Issue by dev-angelo** [codesquad-member-2020/issue-tracker-03#21]
### 1. 로그인 되어있지 않을 경우
![image](https://user-images.githubusercontent.com/58318174/84464718-429c9100-acb0-11ea-9e2c-a646f0025e6a.png)
- ISSUES 버튼: 이슈 목록 화면으로 이동
- Sign in 버튼: OAuth 인증 페이지로 이동

#### 2-1. 기본 상태
![image](https://user-images.githubusercontent.com/58318174/84462630-81c7e380-acaa-11ea-85f0-6bc015df4db0.png)
     - ISSUES 버튼: 이슈 목록 화면으로 이동
     - + 버튼: 사용자가 선택 가능한 기능을 Dropdown
     - User Avatar: 유져 아이디 및 Logout 기능을 Dropdown
  
#### 2-2. 기능 버튼 활성화 상태
![image](https://user-images.githubusercontent.com/58318174/84463278-2991e100-acac-11ea-8306-0e8c7d00468b.png)
     - New Issue 버튼 표시
     - New Milestone 버튼 표시
     - New Label 버튼 표시
  
#### 2-3. 유져 버튼 활성화 상태
![image](https://user-images.githubusercontent.com/58318174/84463290-38789380-acac-11ea-901f-d8ab12d976b2.png)
     - User Id 표시
     - Sign out 버튼 표시

**Comment by 102092** [comment]
와 이렇게 보니까 기능의 흐름을 알 수 있어서 너무 좋아요 👍
